### ISSUE TITLE
Displaying mailings with incorrect html is broken

### ISSUE THREAD

**Issue by floort** [jonge-democraten/hemres#10]
The line "result = inline_css(result)" in models.py throws a XMLSyntaxError.
Lots of old mailings have broken html.

**Comment by trolando** [comment]
Would this be solved with a try catch block around it? That simply "pass" ignores the error for broken HTML?

**Comment by Pi2048** [comment]
That would work, I think. After all, new newsletters are the only ones that use this feature. Older newsletters could just as easily pass through unprocessed.

Obviously be careful to only catch the XMLSyntaxError and not other errors.

**Comment by trolando** [comment]
Ok so it would look like
try:
      result = inline_css(result)
except XMLSyntaxError:
      pass # bad luck

**Comment by trolando** [comment]
Floor can you try this fix?
