### ISSUE TITLE
Security issue: no input validation on uploaded newsletter files

### ISSUE THREAD

**Issue by Pi2048** [jonge-democraten/hemres#11]
The newsletter file uploader allows a broad spectrum of extensions/file types to be uploaded to the static part of the server. I was able to upload and execute a PHP file, which potentially could lead to a full breach of the server.

I strongly urge you to use the filebrowser-safe that is included with Mezzanine. This is the same component Mezzanine uses for uploading media files. We have also used it for our own DocumentListing model.

Furthermore, disabling PHP on the entire Apache virtualhost seems sensible.

**Comment by trolando** [comment]
I will have to investigate further how to use the filebrowser-safe then.

**Comment by trolando** [comment]
For disabling PHP on entire apache virtualhost, perhaps @Pieter1024 could find out how this works and add it to the internal wiki apache conf file?

**Comment by Pi2048** [comment]
I already did this: it is active in the current server config. I will add 
it to the wiki as well.

**Comment by trolando** [comment]
To use filebrowser_safe, what would be the best way to link some file from the filebrowser as an image attachment or as a file attachment?

Of course we could simply forbid either for the end user.

But at least still the templates need to be able to link to images, for example a logo.

My suggestion: we simply use URLs that are generated by filebrowser_safe (that's what it does when you use a image in its editor right?), then during the rendering all image URLs are replaced by content-id references and the images are embedded to the email (autogenerated, no need to manually make content-id fields).

For example by matching on the src field of the img tag, and using a special Django template tag "embed" for all other cases (such as in templates). This tag would work as follows: {% embed 'path/to/image.png' %} would be translated to a reference to an embedded image.

**Comment by Pi2048** [comment]
That sound agreeable to me (as far as I can assess it).
