### ISSUE TITLE
What is the content ID field?

### ISSUE THREAD

**Issue by Pi2048** [jonge-democraten/hemres#12]
When I create a newsletter template and include an image, I disable 'Attach to email'. However, the interface complains that I should enter a 'Content ID'. I have no idea what this is, and neither do our users. Could you make this field go away?

**Comment by trolando** [comment]
The content ID is used in the template to refer to the image in the email_image tag.

**Comment by Pi2048** [comment]
Then why include this intermediate step at all? Can't I just use the filename to refer to the file? This makes using the interface unnecessarily complicated.

If using the Content ID is necessary after all, at least explain how it works.

**Comment by trolando** [comment]
If I use filebrowser-safe, then maybe this whole content id is no longer necessary.
