### ISSUE TITLE
Security issue: Content Managers can send out email newsletters

### ISSUE THREAD

**Issue by Pi2048** [jonge-democraten/hemres#14]
A resourceful Content Manager may send out email newsletters without the consent of the person with Newsletter to Lists-permissions.

A Content Manager who only has Newsletters permissions can still access the URL that admins use to send out the newsletter. The easy structure of this URL facilitates guessing (e.g. 'https://website.url/nieuwsbrief/process/3').

I would propose checking whether the user has the appropriate permission (before allowing him to visit this URL). Just hiding it will probably never be enough.

**Comment by trolando** [comment]
Probably just adding an annotation is sufficient for this, checking that they have the permission to "change" a NewsletterToList for example.
